import { Poppins } from "next/font/google";
import Script from 'next/script';

// Specify the weights you want to use
const poppins = Poppins({ 
  subsets: ["latin"], 
  weight: ["400", "600"] // Use 'weight' instead of 'weights'
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <Script
          src={`https://www.googletagmanager.com/gtag/js?id=G-P35QPLTGWT`}
          strategy="afterInteractive"
        />
        <Script id="google-analytics" strategy="afterInteractive">
          {`
            window.dataLayer = window.dataLayer || [];
            function gtag(){dataLayer.push(arguments);}
            gtag('js', new Date());
            gtag('config', 'G-P35QPLTGWT');
          `}
        </Script>
      </head>
      <body className={poppins.className}>{children}</body>
    </html>
  );
}